apiVersion: v1
data:
    admin.password: ENC[AES256_GCM,data:XNOlgL5BbmXOvoFc4PiI4j2RJe5vePGWQjkylRf15dnx5yXkuxHHPapWZ9+s7qtoZFL9MM8tu/tCOrJ4NyUXBDSErKKJxnSYzweXMsKOVZM=,iv:O33ozfW/Pu+qCItL/8AmF4QdKHwUlP3gHzqTJSJV9wY=,tag:DDKrVmy205v9+PF7nIQHPg==,type:str]
    server.secretkey: ENC[AES256_GCM,data:PrVX3tpn2CpxWiWeJkJr3QKOAdTcFWecpmrH6LkeFuxRr7NTc5oTPqku8zTLOGkJqU5kJBoU+e3SzAyd,iv:eEcY0vLVY5KwzDeJ7bsC94tJMtHYnyqI3pXMFJmBWZ0=,tag:Ywi795ksdb5I4iZoxODjZg==,type:str]
kind: Secret
metadata:
    name: argocd-secret
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/comprehensive-turkey/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2021-11-28T01:18:53Z"
          enc: CiQAL+g/6cpOkMkhI+0NmgdXokltzFTGOBAPqAZhPcG9zAH4MRUSSQAl30jLc8fIUBsoJMz6+u+m89CCNfxB2gjN//tb3IhH5/3p5qk706bLMVQf/tRcamnJMD49SDIOtV+wKvfLUp6Dfat6DSETRaI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-28T01:18:55Z"
    mac: ENC[AES256_GCM,data:mSFbG8lqLMuEJEI+7FckurYU8nRRZZ9PGPfGgXpahanfPP5UrvxnM/Vi0ODj/F1GSJ9+UFsIhn6417Nn9L6xGAx+F0e/NtPKXH9HZX/q7Qg1ahcY4wcal7F1x5ARJUX2uqJBc+HagntweBKwh8bIQDLgdNPB4Ovfq3k1xfS5MGs=,iv:O5KfTGiQ4BgAuBmqljdj8w9Vpg6U4DFd0qhppriqfW4=,tag:eg5MADaKFznHWYCXaR76WA==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.1
