apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitopsRepoUrl }}
    targetRevision: HEAD
    path: charts/argocd-apps
    helm:
      parameters:
        - name: repoUrl
          value: {{ .Values.gitopsRepoUrl }}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
