{{ range $secretName, $secret := .Values.secrets }}
apiVersion: v1
data: {{ $secret.data | toYaml | nindent 2 }}
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $secret.namespace }}
  annotations:
    {{ if $secret.otherNamespaces }}
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ join "," $secret.otherNamespaces }}
    {{ end }}
---
{{ end }}
