{{ range $secretName, $secret := .Values.secrets }}
apiVersion: v1
data:
    {{ range $key, $value := $secret.data }}
    {{ $key }}: {{ $value }}
    {{ end }}
kind: Secret
metadata:
    name: {{ $secretName }}
    namespace: {{ $secret.namespace }}
---
{{ end }}
