argo-cd:
  configs:
    secret:
      createSecret: false
charts:
  - cert-manager
  - external-dns
  - ingress-nginx
  - kubernetes-reflector
sops-secrets-operator:
  gcp:
    enabled: true
    existingSecretName: gcp-sa

# secrets:
#   example-secret:
#     namespace: example-ns
#     data:
#       key: PHZhbHVlPgo=

secrets: {}
