argo-cd:
  configs:
    secret:
      createSecret: false
sops-secrets-operator:
  gcp:
    enabled: true
    existingSecretName: gcp-sa
secrets:
  gcp-sa:
    otherNamespaces:
      - external-dns
    data:
      key.json: PFJFREFDVEVEPgo=
gitopsRepoUrl: https://github.com/comprehensive-turkey/gitops
