on:
  push:
    branches:
      - master
jobs:
  pulumi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcp_sa=$(cat $GOOGLE_APPLICATION_CREDENTIALS | base64) yq e -i '.secrets.gcp-sa.data."key.json" = strenv(gcp_sa)' argocd/values.yaml
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          MONGODB_ATLAS_ORGID: ${{ secrets.MONGODB_ATLAS_ORGID }}
          MONGODB_USERPASS: ${{ secrets.MONGODB_USERPASS }}
